jj_flix/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [path('admin/', admin.site.urls),
               path('', include('video.urls', namespace = 'video'))]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

video/urls.py
from django.urls import path, reverse_lazy
from .views import HomePage, HomeVideos, DetalhesVideo, PesquisaVideo, EditarPerfil, CriarConta
from django.contrib.auth import views as auth_view

app_name = 'video'

urlpatterns = [path('', HomePage.as_view(), name = 'homepage'),
               path('videos/', HomeVideos.as_view(), name = 'homevideos'),
               path('videos/<int:pk>', DetalhesVideo.as_view(), name = 'detalhesvideo'),
               path('pesquisa/', PesquisaVideo.as_view(), name = 'pesquisavideo'),
               path('login/', auth_view.LoginView.as_view(template_name = 'login.html'), name = 'login'),
               path('logout/', auth_view.LogoutView.as_view(template_name = 'logout.html'), name = 'logout'),
               path('editarperfil/<int:pk>', EditarPerfil.as_view(), name = 'editarperfil'),
               path('criarconta/', CriarConta.as_view(), name = 'criarconta'),
               path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name = 'editarperfil.html', success_url = reverse_lazy('video:homevideos')), name = 'mudarsenha')]

video/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

LISTA_CATEGORIAS = (('JOCA', 'Joca'),
                    ('JUAN', 'Juan'),
                    ('EMDUPLA', 'Em Dupla'),
                    ('ESCOLA', 'Na escola'),
                    ('EXTRAS', 'Extras'))

class Video(models.Model):
    titulo = models.CharField(max_length = 50)
    thumb = models.ImageField(upload_to = 'thumb_videos')
    descricao = models.TextField(max_length = 200)
    categoria = models.CharField(max_length = 10, choices = LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default = 0)
    data_criacao = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.titulo

class Episodio(models.Model):
    filme = models.ForeignKey('Video', related_name = 'episodios', on_delete = models.CASCADE)
    titulo = models.CharField(max_length = 100)
    video = models.URLField()
    thumbnail = models.ImageField(upload_to = 'thumb_videos')

    def __str__(self):
        return self.filme.titulo + " - " + self.titulo

class Usuario(AbstractUser):
    videos_vistos = models.ManyToManyField('Video')

video/forms.py
from django.contrib.auth.forms import UserCreationForm
from.models import Usuario
from django import forms

class FormHomePage(forms.Form):
    email = forms.EmailField(label = False)

class CriaContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

video/views.py
from django.shortcuts import render, redirect, reverse
from .models import Video, Usuario
from .forms import CriaContaForm, FormHomePage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin

class HomePage(FormView):
    template_name = 'homepage.html'
    form_class = FormHomePage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('video:homevideos')
        else:
            return super().get(request, *args, **kwargs)

    def get_success_url(self):
        email = self.request.POST.get('email')
        usuarios = Usuario.objects.filter(email = email)
        if usuarios:
            return reverse('video:login')
        else:
            return reverse('video:criarconta')

class HomeVideos(LoginRequiredMixin, ListView):
    template_name = 'homevideos.html'
    model = Video

class DetalhesVideo(LoginRequiredMixin, DetailView):
    template_name = 'detalhesvideo.html'
    model = Video

    def get(self, request, *args, **kwargs):
        video = self.get_object()
        video.visualizacoes += 1
        video.save()
        usuario = request.user
        usuario.videos_vistos.add(video)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DetalhesVideo, self).get_context_data(**kwargs)
        videos_relacionados = self.model.objects.filter(categoria = self.get_object().categoria)[0:4]
        context['videos_relacionados'] = videos_relacionados
        return context

class PesquisaVideo(LoginRequiredMixin, ListView):
    template_name = 'pesquisa.html'
    model = Video

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = self.model.objects.filter(titulo__icontains = termo_pesquisa)
            return object_list
        else:
            return None

class EditarPerfil(LoginRequiredMixin, UpdateView):
    template_name = 'editarperfil.html'
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('video:homevideos')

class CriarConta(FormView):
    template_name = 'criarconta.html'
    form_class = CriaContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('video:login')

templates/base.html
<!DOCTYPE html>
<html lang = 'en'>
<head>
    <meta charset = 'UTF-8'>
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link href = 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css' rel = 'stylesheet' integrity = 'sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65' crossorigin = 'anonymous'>
    <script src = 'https://cdn.tailwindcss.com'></script>
    {% block head %}
    {% endblock %}
</head>
<body class= 'bg-black text-gray-100 font-primary'>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <script>
    const nav = document.querySelector('nav');

    document.addEventListener("scroll", e => {
        if (window.scrollY > 100) {
            nav.classList.add('bg-gray-900');
            if (window.scrollY > window.innerHeight) {
                nav.classList.add('invisible');
            } else {
                nav.classList.remove('invisible');
            }
        } else {
            nav.classList.remove('bg-gray-900');
            nav.classList.remove('invisible');
        }
    });
    </script>
    <script type = 'module' src = 'https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js'></script>
    <script nomodule src = 'https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js'></script>
</body>
</html>

templates/navbar.html
{% load static %}

<nav class = 'w-full flex justify-between items-center py-3 px-4 fixed z-50'>
    <div class = 'w-6/12'>
        <a href = '/'>
            <img class = 'w-2/12' src = "{% static 'images/jj_flix.png' %}">
        </a>
    </div>

    <div class = 'w-6/12 flex flex-nowrap justify-end'>
        {% if user.is_authenticated %}
        <div class = 'mr-2'>
            <form method = 'get' action = "{% url 'video:pesquisavideo' %}">
                <input type = 'text' class = 'py-1 px-2 rounded-md text-black' name = 'query' value = '{{ request.GET.query }}' placeholder = 'Pesquisar...'>
                <input type = 'submit' value = ''>
            </form>
        </div>
        {% endif %}
        <div class = 'mr-2'>
            {% if user.is_authenticated %}
            <form method = 'post' action = "{% url 'video:logout' %}">
                {% csrf_token %}
                <button class = 'bg-red-600 text-white py-1 px-3 rounded-md' type = 'submit'>
                    Sair
                </button>
            </form>
            {% else %}
            <a href = "{% url 'video:login' %}">
                <button class = 'bg-red-600 text-white py-1 px-3 rounded-md'>
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class = 'mr-2'>
            <a href = "{% url 'video:editarperfil' user.pk %}">
                <button class = 'bg-red-600 text-white py-1 px-3 rounded-md'>
                    Editar Perfil
                </button>
            </a>
        </div>
        {% endif %}
    </div>
</nav>

video/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    Criar Conta
{% endblock %}

{% block content %}
<header class = 'min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-contain bg-center' style = "background-image: url('{% static 'images/bg_jjflix.png' %}');">
        <div class = 'z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col'>
            <form method = 'post'>
                {% csrf_token %}
                <fieldset class = 'form-group'>
                    <legend class = 'border-bottom mb-4'>
                       Crie uma conta para continuar
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                  <button class = 'bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md' type = 'submit'>
                      Criar Conta
                  </button>
            </form>

        </div>
    </header>

    <footer class = 'px-5 py-10'>
        <ul class = 'flex justify-between items-center'>

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Marques</li>
        </ul>
    </footer>
{% endblock %}

video/templates/detalhesvideo.html
{% extends 'base.html' %}

{% block titulo %}
    Detalhes
{% endblock %}

{% block content %}
    <main class = 'bg-primary_black min-h-screen w-full'>
        <section class = 'h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover'
            style = "background-image: url('{{ object.thumb.url }}')">
            <div>
                <h2 class = 'text-6xl font-semibold text-white my-4'>
                    {{ object.titulo }}
                </h2>
                <p class = 'w-11/12 md:w-5/12 font-medium text-white my-4'>
                    {{ object.descricao|slice:':100' }}...
                </p>
            </div>
        </section>
  
        <section class = 'bg-primary_black flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-3xl font-medium'>
                    Episódios
                </h2>
                <br />
                <ul class = 'episodios-list'>
                    {% for episodio in object.episodios.all %}
                        <li class = 'episodio-item flex items-center'>
                            <span class = 'episodio-contador mr-2'>
                                Episódio {{ forloop.counter }}
                            </span>
                            <h3 class = 'episodio-title'>
                                {{ episodio.titulo }}
                            </h3>
                            &nbsp; - &nbsp;
                            <a href = '{{ episodio.video.url }}' >
                                <img src = '{{ episodio.thumbnail.url }}' alt = '{{ episodio.titulo }}' class = 'episodio-thumbnail h-20 w-20 object-cover'/>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
          </section>
  
        <section class = 'bg-primary_black flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-2xl font-medium'>
                    Relacionados
                </h2>
                <div class = 'flex flex-wrap items-center min-w-full movie_lis'>
                {% for video in videos_relacionados %}
                    <div class = 'm-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96'>
                        <a href = "{% url 'video:detalhesvideo' video.pk %}">
                            <img src = '{{ video.thumb.url }}' class = 'object-cover w-full h-full' alt = ''/>
                        </a>
                    </div>
                {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

video/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    Editar Perfil
{% endblock %}

{% block content %}
    <header class = 'min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-contain bg-center' style = "background-image: url('{% static 'images/bg_jjflix.png' %}');">
        <div class = 'z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col'>
            <h2 class = 'text-2xl'>
                {{ user.username }}
            </h2>

            <form method = 'post'>
                {% csrf_token %}
                <fieldset class = 'form-group'>
                    <legend class = 'border-bottom mb-4'>
                        Edite os campos abaixo para editar seu perfil
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                <button class = 'bg-red-600 py-1 px-3 text-white md:text-lg rounded-md' type = 'submit'>
                    Editar Perfil
                </button>
            </form>
            <small>
                <a href = "{% url 'video:mudarsenha' %}">
                    Quer mudar sua senha?
                </a>
            </small>
        </div>
    </header>

    <footer class = 'px-5 py-10'>
        <ul class = 'flex justify-between items-center'>

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Marques</li>
        </ul>
    </footer>
{% endblock %}

video/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Homepage
{% endblock %}

{% block head %}
<style>
    #id_email{
    width: 100%;
    height: 100%;
    color: #000000;
    padding: 5px 5px;
    }
</style>
{% endblock %}

{% block content %}
    <header class = 'min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-contain bg-center' style = "background-image: url('{% static 'images/bg_jj_flix.png' %}');">
        <div class = 'z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col'>

            <h1 class = 'font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center'>
                Videos da J&J Flix, tudo em um só lugar.
            </h1>
            <h3 class = 'text-xl md:text-xl py-5'>
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class = 'text-sm md:text-lg pb-3'>
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class = 'w-full flex justify-center'>
                <div class = 'flex justify-center items-center w-11/12 md:w-10/12'>
                    <form method = 'post' class = 'w-6/12 justify-center'>
                        {% csrf_token %}
                        <div class = 'flex flex-grow items-stretch'>
                            {{ form }}
                        <button class = 'bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl' type = 'submit'>
                            <span>
                                Acessar
                            </span>
                            <ion-icon name = 'chevron-forward-outline' class = 'text-2xl'></ion-icon>
                        </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <section class = 'flex flex-col md:flex-row items-center border-gray-900 border-b-8' style = 'min-height: 70vh;'>
        <div class = 'md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10'>
            <h2 class = 'md:text-5xl text-4xl font-semibold mb-4'>
                Enjoy on your TV.
            </h2>
            <h5 class = 'md:text-xl text-lg'>
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class = 'md:w-1/2 flex justify-center items-center'>
            <img src= " {% static 'images/tv.png' %}" class = 'w-8/12' alt = ''>
        </div>
    </section>

    <section class = 'flex flex-col md:flex-row items-center border-gray-900 border-b-8' style = 'min-height: 70vh;'>
        <div class = 'md:w-1/2 flex justify-center items-center'>
            <img src = "{% static 'images/mobile-0819.jpg' %}" class = 'w-8/12' alt = ''>
        </div>
        <div class = 'md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10'>
            <h2 class = 'md:text-5xl text-4xl font-semibold mb-4'>
                Download your shows to watch offline.
            </h2>
            <h5 class = 'md:text-xl text-lg'>
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
    </section>

    <section class = 'flex flex-col md:flex-row items-center border-gray-900 border-b-8' style = 'min-height: 70vh;'>
        <div class = 'md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10'>
            <h2 class = 'md:text-5xl text-4xl font-semibold mb-4'>
                Create profiles for kids.
            </h2>
            <h5 class = 'md:text-xl text-lg'>
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class = 'md:w-1/2 flex justify-center items-center'>
            <img src = "{% static 'images/netflix_kid.png' %}" class = 'w-8/12' alt = ''>
        </div>
    </section>

    <footer class = 'px-5 py-10'>
        <ul class = 'flex justify-between items-center'>

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Marques</li>
        </ul>
    </footer>
{% endblock %}

video/templates/homevideos.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Videos
{% endblock %}

{% block head %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'css/carrossel.css' %}">
{% endblock %}

{% block content %}
    <main class = 'bg-primary_black min-h-screen w-full'>
        <section class = 'h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover' style = "background-image: url('{{ video_destaque.thumb.url }}')">
            <div>
                <h2 class = 'text-6xl font-semibold text-white my-4'>
                    {{ video_destaque.titulo }}
                </h2>
                <p class = 'w-11/12 md:w-5/12 font-medium text-white my-4'>
                    {{ video_destaque.descricao }}
                </p>
                <div class = 'flex my-4'>
                    <a href = "{% url 'video:detalhesvideo' video_destaque.pk %}">
                        <button class = 'flex items-center bg-white py-2 px-5 rounded-md' style = 'color:black'>
                            <ion-icon name = 'play' class = 'text-2xl'></ion-icon>
                            <span class = 'ml-3 font-medium'>
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>

        <section class = 'bg-primary_black flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-2xl font-medium'>
                    O que há de novo
                </h2>
                <div class = 'wrapper'>
                    <section id = 'section1' class = 'flex flex-nowrap items-center justify-center space-x-8'>
                        <a href = '#section2' class = 'arrow__btn text-6xl page'>‹</a>
                        {% for video in lista_videos_recentes %}
                            {% if forloop.counter < 5 %}
                                <div class = 'item h-64 w-1/4 m-4'>
                                    <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                        <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <a href = '#section2' class = 'arrow__btn text-6xl'>›</a>
                    </section>
                    {% if lista_videos_recentes|length > 4 %}
                    <section id = 'section2' class = 'flex flex-nowrap items-center justify-center'>
                        <a href = '#section1' class = 'arrow__btn text-6xl'>‹</a>
                        {% for video in lista_videos_recentes %}
                            {% if forloop.counter > 4 %}
                                <div class = 'item h-64 w-1/4 m-4'>
                                    <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                        <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                    </a>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <a href = '#section1' class = 'arrow__btn text-6xl'>›</a>
                    </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class = 'bg-primary_black flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-2xl font-medium'>
                    Mais vistos
                </h2>
                <div class = 'wrapper'>
                    <section id = 'section1emalta' class = 'flex flex-nowrap items-center justify-center space-x-8'>
                        <a href = '#section2emalta' class = 'arrow__btn text-6xl page'>‹</a>
                            {% for video in lista_videos_emalta %}
                                {% if forloop.counter < 5 %}
                                    <div class = 'item h-64 w-1/4 m-4'>
                                        <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                            <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        <a href = '#section2emalta' class = 'arrow__btn text-6xl'>›</a>
                    </section>
                    {% if lista_videos_emalta|length > 4 %}
                        <section id = 'section2emalta' class = 'flex flex-nowrap items-center justify-center'>
                            <a href = '#section1emalta' class = 'arrow__btn text-6xl'>‹</a>
                                {% for video in lista_videos_emalta %}
                                    {% if forloop.counter > 4 %}
                                        <div class = 'item h-64 w-1/4 m-4'>
                                            <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                                <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                            </a>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            <a href = '#section1emalta' class = 'arrow__btn text-6xl'>›</a>
                        </section>
                    {% endif %}
                </div>
            </div>
        </section>

        <section class = 'bg-primary_black flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-2xl font-medium'>
                    Assistir de novo
                </h2>
                <div class = 'wrapper'>
                    <section id = 'section1vistos' class = 'flex flex-nowrap items-center justify-center space-x-8'>
                        <a href = '#section2vistos' class = 'arrow__btn text-6xl page'>‹</a>
                            {% for video in request.user.videos_vistos.all %}
                                {% if forloop.counter < 5 %}
                                    <div class = 'item h-64 w-1/4 m-4'>
                                        <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                            <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                        </a>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        <a href = '#section2vistos' class = 'arrow__btn text-6xl'>›</a>
                    </section>
                    {% if request.user.videos_vistos.all|length > 4 %}
                        <section id = 'section2vistos' class = 'flex flex-nowrap items-center justify-center'>
                            <a href = '#section1vistos' class = 'arrow__btn text-6xl'>‹</a>
                                {% for video in request.user.videos_vistos.all %}
                                    {% if forloop.counter > 4 %}
                                        <div class = 'item h-64 w-1/4 m-4'>
                                            <a href = "{% url 'video:detalhesvideo' video.pk %}">
                                                <img src = '{{ video.thumb.url }}' class = 'rounded-md w-full h-full object-cover'>
                                            </a>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            <a href = '#section1vistos' class = 'arrow__btn text-6xl'>›</a>
                        </section>
                    {% endif %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}

video/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
    Login
{% endblock %}

{% block content %}
    <header class = 'min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-contain bg-center' style = "background-image: url('{% static 'images/bg_jjflix.png' %}');">
        <div class = 'z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col'>
            <form method = 'post'>
                {% csrf_token %}
                <fieldset class = 'form-group'>
                    <legend class = 'border-bottom mb-4'>
                        Faça Login para continuar
                    </legend>
                    {{ form|crispy }}
                </fieldset>
                    <button class = 'bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md' type = 'submit'>
                        Fazer Login
                    </button>
            </form>
            <small>
                Não tem uma conta ainda?
                <p>
                    <a href = "{% url 'video:criarconta' %}">
                        Clique aqui para criar uma conta
                    </a>
                </p>
            </small>
        </div>
    </header>

    <footer class = 'px-5 py-10'>
        <ul class = 'flex justify-between items-center'>

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Marques</li>
        </ul>
    </footer>
{% endblock %}

video/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Logout
{% endblock %}

{% block content %}
    <header class = 'min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat bg-contain bg-center' style = "background-image: url('{% static 'images/bg_jjflix.png' %}');">
        <div class = 'z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col'>
            <h2 class = 'text-2xl'>
                Você saiu da sua conta
            </h2>
            <div class = 'flex flex-nowrap justify-center space-x-5 p-5'>
                <a href = "{% url 'video:login' %}">
                    <button class = 'bg-red-600 py-1 px-3 text-white md:text-lg rounded-md'>
                        Fazer Login
                    </button>
                </a>
                <a href = "{% url 'video:criarconta' %}">
                    <button class = 'bg-red-600 py-1 px-3 text-white md:text-lg rounded-md'>
                        Criar uma Conta
                    </button>
                </a>
            </div>
        </div>
    </header>

    <footer class = 'px-5 py-10'>
        <ul class = 'flex justify-between items-center'>

            <li>&copy; 2024</li>
            <li> Feito com Python (Django)</li>
            <li>Marques</li>
        </ul>
    </footer>
{% endblock %}

video/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
    Pesquisa
{% endblock %}

{% block content %}
    <main class = 'bg-primary_black min-h-screen w-full'>
        <section class = 'bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class = 'p-8 w-10/12 relative'>
                <h2 class = 'text-gray-200 text-2xl font-medium'>
                    Resultados da Busca
                </h2>
                <div class = 'flex flex-wrap items-center min-w-full movie_lis'>
                    {% for video in object_list %}
                    <div class = 'm-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96'>
                        <a href = "{% url 'video:detalhesvideo' video.pk %}">
                            <img src = '{{ video.thumb.url }}' class = 'object-cover w-full h-full' alt = ''>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </main>
{% endblock %}